<a href="https://colab.research.google.com/github/prakharraj11/Cognitive-Computing/blob/main/Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignment 4**
Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element

b) Multiply 3 with all the elements

c) Divide every element by 2

In [11]:
import numpy as np
a = np.arange(1,6)
print(a)
print("adding 2 to all elements")
print(a+2)
print("Multiplying by 3")
print(a*3)
print("Dividing each element by 2")
print(a/2)

[1 2 3 4 5]
adding 2 to all elements
[3 4 5 6 7]
Multiplying by 3
[ 3  6  9 12 15]
Dividing each element by 2
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

b) Find the most frequent value and their indice(s) in the following arrays:

i. x = np.array([1,2,3,4,5,1,2,1,1,1])

ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [31]:
b = np.array([1,2,3,6,4,5])
c = np.flip(b)
print(b)
print("Printing reverse")
print(c)

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

print("For array x")
uni, freq = np.unique(x,return_counts=True)
a = np.where(freq==(max(freq)))
print(uni[a])
print(np.where(x==uni[a]))

print("For array y")
uni, freq = np.unique(y,return_counts=True)
a = np.where(freq==(max(freq)))
print(uni[a])
print(np.where(y==uni[a][0]))

[1 2 3 6 4 5]
Printing reverse
[5 4 6 3 2 1]
For array x
[1]
(array([0, 5, 7, 8, 9]),)
For array y
[1 3]
(array([0, 1, 2]),)


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [37]:
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [75]:
Prakhar = np.linspace(10,100,25)
print(Prakhar)
print("Dimensions of the array = ",Prakhar.ndim)
print("Shape of the array = ",Prakhar.shape)
print("Total elements = ",np.size(Prakhar))
print("Datatype ",Prakhar.dtype)
print("Total size of array in bytes = ",Prakhar.itemsize * Prakhar.size)
print("Transposing ")
Prakhar = Prakhar.reshape
print(Prakhar)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array =  1
Shape of the array =  (25,)
Total elements =  25
Datatype  float64
Total size of array in bytes =  200
Transposing 
<built-in method reshape of numpy.ndarray object at 0x7bca627d7b10>


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [89]:
ucs420 = np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420)
print()
print("Mean of the given array = ",np.mean(ucs420))
print("Median of the given array = ",np.median(ucs420))
print("Maimum value = ",np.max(ucs420))
print("Minimum value = ",np.min(ucs420))
print("Maimum value = ",np.unique(ucs420))
print("Reshaping")
reshaped = ucs420.reshape(4,3)
print(reshaped)
print("Resizing")
resized = np.resize(ucs420,[2,3])
print(resized)

[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean of the given array =  43.333333333333336
Median of the given array =  37.5
Maimum value =  90
Minimum value =  10
Maimum value =  [10 15 20 30 35 40 50 60 70 80 90]
Reshaping
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resizing
[[10 20 30]
 [40 50 60]]
